import type { Route } from '@/ai/brain';

/**
 * Mock dataset for AI route recommendation testing.
 * Simulates diverse trails, distances, elevations, and surfaces.
 */
export const mockRoutes: Route[] = [
  {
    id: 'r1',
    name: 'Coastal Easy Trail',
    distance_km: 8.5,
    elevation_gain_m: 120,
    surface_type: 'trail',
    scenic_score: 9,
    popularity_score: 8,
    start_lat: 40.7128,
    start_lon: -74.006,
  },
  {
    id: 'r2',
    name: 'Mountain Ridge Challenge',
    distance_km: 15,
    elevation_gain_m: 900,
    surface_type: 'trail',
    scenic_score: 10,
    popularity_score: 9,
    start_lat: 40.7580,
    start_lon: -73.9855,
  },
  {
    id: 'r3',
    name: 'City Park Loop',
    distance_km: 5,
    elevation_gain_m: 30,
    surface_type: 'road',
    scenic_score: 6,
    popularity_score: 9.5,
    start_lat: 40.7829,
    start_lon: -73.9654,
  },
  {
    id: 'r4',
    name: 'Rolling Hills Circuit',
    distance_km: 10,
    elevation_gain_m: 400,
    surface_type: 'trail',
    scenic_score: 8,
    popularity_score: 7,
    start_lat: 40.7589,
    start_lon: -73.9851,
  },
  {
    id: 'r5',
    name: 'Forest Adventure Path',
    distance_km: 12,
    elevation_gain_m: 500,
    surface_type: 'mixed',
    scenic_score: 8.5,
    popularity_score: 6,
    start_lat: 40.7614,
    start_lon: -73.9776,
  },
  {
    id: 'r6',
    name: 'Riverside Flat Run',
    distance_km: 6,
    elevation_gain_m: 10,
    surface_type: 'road',
    scenic_score: 7,
    popularity_score: 8.5,
    start_lat: 40.7489,
    start_lon: -73.9680,
  },
  {
    id: 'r7',
    name: 'Urban Sprint Route',
    distance_km: 3,
    elevation_gain_m: 15,
    surface_type: 'road',
    scenic_score: 5,
    popularity_score: 7,
    start_lat: 40.7484,
    start_lon: -73.9857,
  },
  {
    id: 'r8',
    name: 'Long Distance Trail',
    distance_km: 21,
    elevation_gain_m: 650,
    surface_type: 'trail',
    scenic_score: 9.5,
    popularity_score: 5,
    start_lat: 40.7791,
    start_lon: -73.9627,
  },
  {
    id: 'r9',
    name: 'Technical Hill Repeats',
    distance_km: 4,
    elevation_gain_m: 300,
    surface_type: 'trail',
    scenic_score: 6,
    popularity_score: 4,
    start_lat: 40.7505,
    start_lon: -73.9934,
  },
  {
    id: 'r10',
    name: 'Half Marathon Training Loop',
    distance_km: 21.1,
    elevation_gain_m: 200,
    surface_type: 'mixed',
    scenic_score: 8,
    popularity_score: 7.5,
    start_lat: 40.7589,
    start_lon: -73.9851,
  },
];
